wardley-beta
title Animal Farm - March 2024
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component "PUBLISHING_INDUSTRY" [0.93, 0.62]
component "POLITICAL_SATIRE" [0.88, 0.82]
component "SOVIET_UNION" [0.70, 0.75]
component "ALLEGORY" [0.68, 0.68]

component "ANIMAL_FARM_NOVEL" [0.83, 0.56]
component "PLOT_AND_STORY" [0.54, 0.70]
component "CHARACTERS" [0.42, 0.64]
component "SETTING" [0.59, 0.59]
component "THEMES" [0.40, 0.52]
component "WRITING_STYLE" [0.66, 0.46]

component "Animal_Rebellion" [0.44, 0.74]
component "Rise_of_Pigs" [0.50, 0.69]
component "Napoleon" [0.34, 0.61]
component "Snowball" [0.37, 0.66]
component "Boxer" [0.39, 0.59]
component "Manor_Farm" [0.51, 0.59]
component "Animalism" [0.54, 0.56]
component "Totalitarianism" [0.26, 0.54]
component "Revolution_Betrayed" [0.37, 0.48]
component "Corruption_of_Power" [0.29, 0.48]
component "Simple_Language" [0.52, 0.45]
component "Irony_And_Satire" [0.59, 0.41]

"POLITICAL_SATIRE" -> "ANIMAL_FARM_NOVEL"
"SOVIET_UNION" -> "ANIMAL_FARM_NOVEL"
"ALLEGORY" -> "ANIMAL_FARM_NOVEL"
"ANIMAL_FARM_NOVEL" -> "PLOT_AND_STORY"
"ANIMAL_FARM_NOVEL" -> "CHARACTERS"
"ANIMAL_FARM_NOVEL" -> "SETTING"
"ANIMAL_FARM_NOVEL" -> "THEMES"
"ANIMAL_FARM_NOVEL" -> "WRITING_STYLE"
"PLOT_AND_STORY" -> "Animal_Rebellion"
"PLOT_AND_STORY" -> "Rise_of_Pigs"
"CHARACTERS" -> "Napoleon"
"CHARACTERS" -> "Snowball"
"CHARACTERS" -> "Boxer"
"SETTING" -> "Manor_Farm"
"SETTING" -> "Animalism"
"THEMES" -> "Totalitarianism"
"THEMES" -> "Revolution_Betrayed"
"THEMES" -> "Corruption_of_Power"
"WRITING_STYLE" -> "Simple_Language"
"WRITING_STYLE" -> "Irony_And_Satire"
"SOVIET_UNION" -> "THEMES"
"POLITICAL_SATIRE" -> "WRITING_STYLE"
"ALLEGORY" -> "CHARACTERS"
"ALLEGORY" -> "SETTING"
"PUBLISHING_INDUSTRY" -> "ANIMAL_FARM_NOVEL"

