wardley-beta
title Gaming Industry - Community. NOV 2023
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

note "OOG' = 'Out of game" [0.97, 0.02]

component Diegetic [0.21, 0.21]
component "Non-diegetic" [0.21, 0.67]

component Businesses [1.00, 0.73]
component Value [0.91, 0.64]
component Revenue [0.94, 0.70]
component Broad audience [0.92, 0.73]

component Communities [0.99, 0.86]
component Identity [0.92, 0.79]
component Purpose [0.89, 0.90]
component Organisation [0.95, 0.89]

component Players [0.99, 0.63]
component Values [0.86, 0.84]

component Games [0.86, 0.47]

component "I/O" [0.8, 0.43]
pipeline "I/O" {
  component VR [0.11]
  component XR [0.16]
  component Motion tracking [0.29]
  component Camera [0.49]
  component Voice [0.68]
  component Touch [0.74]
  component Screen [0.79]
  component Mouse [0.83]
  component Keyboard [0.87]
  component Buttons [0.91]
}

component Channels [0.70, 0.48]
pipeline Channels {
  component Heavy multimodality (Discord) [0.23]
  component Custom platform (leagues) [0.43]
  component Steam [0.6]
  component Platforms [0.69]
  component Websites [0.79]
  component Synchronous text chat [0.88]
  component Asynchronous text chat [0.94]
}

component OOG community content [0.6, 0.43]
pipeline OOG community content {
  component "In-game photography" [0.1]
  component eSports events [0.18]
  component Casual events (PAX) [0.23]
  component "Lore/Wiki Maintainers" [0.28]
  component Tournaments and leagues [0.48]
  component Live streamers [0.55]
  component YouTubers [0.62]
  component Merch [0.67]
  component Visual arts [0.7]
  component Warez groups [0.74]
  component Fanfiction [0.78]
  component Game journalism [0.8]
  component Game reviews [0.82]
  component Guides and tutorials [0.85]
}

component Governance and rules [0.50, 0.41]
pipeline Governance and rules {
  component DAOs [0.04]
  component Flexable AI automated tools [0.14]
  component Self moderation and regulation [0.25]
  component Moderators and officials [0.52]
  component Community and peer moderation [0.64]
  component Rigid automated tools [0.75]
  component Customer support [0.79]
  component Game mechanics [0.87]
  component Regulations and laws [0.91]
  component Social norms [0.95]
}

component Game Mods [0.40, 0.42]
pipeline Game Mods {
  component Heavily altered mechanics [0.22]
  component Ingame [0.28]
  component Out of game [0.56]
  component Aesthetic modifications [0.63]
  component API or source code [0.67]
  component Standards [0.76]
  component Asset stores [0.83]
}

component Tools [0.30, 0.42]
pipeline Tools {
  component AI tool entailment [0.03]
  component AI toolchains [0.1]
  component AI first novel tools [0.18]
  component AI assisted traditional tools [0.23]
  component Game creation platforms [0.66]
  component "Sculpture, graphics, audio" [0.8]
  component Game engines [0.86]
}

component "Logs / Recordings" [0.07, 0.76]

component Data [0.03, 0.87]

Communities -> Organisation
Communities -> Purpose
Communities -> Identity
Communities -> Revenue
Communities -> Values
Businesses -> Revenue
Revenue -> Broad audience
Revenue -> Value
Value -> Games
Identity -> Games
Games -> "I/O"
Organisation -> Channels
Tools -> "Non-diegetic"
Organisation -> Governance and rules
Governance and rules -> "Logs / Recordings"
"Logs / Recordings" -> Data
Game Mods -> Ingame
Game Mods -> Out of game
Trolls -> Emotional responses
Trolls -> Imperfect rule enforcement
AI tool entailment -> "Logs / Recordings"
Flexable AI automated tools -> "Logs / Recordings"
Communities -> OOG community content
OOG community content -> Game Mods
Game Mods -> Tools
Games -> Tools
Tools -> Diegetic

