wardley-beta
title defence - the grey zone
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component government [0.95, 0.67] label [13, -4]
component "private / proxy" [0.88, 0.61] label [3, -25]
component sovereignty [0.76, 0.59] label [4, -7]
pipeline sovereignty {
  component crypto [0.34] label [-43, 31]
  component competition [0.39] label [-105, -16]
  component economic [0.43] label [-49, 48]
  component cyber [0.52] label [-51, -30]
  component culture [0.64] label [-5, 26]
  component territory [0.69] label [16, 7]
}

component theatre [0.60, 0.60] label [-40, -8]
pipeline theatre {
  component finance [0.43] label [-66, 3]
  component social media [0.54] label [-98, 31]
  component space [0.57] label [-25, 24]
  component electronic [0.62] label [-24, 26]
  component propaganda [0.65] label [0, -16]
  component land [0.69] label [24, 6]
}

component landscape [0.24, 0.60] label [6, -7]
pipeline landscape {
  component virtual landscape [0.44] label [-94, -27]
  component supply chain [0.51] label [-39, 48]
  component physical landscape [0.69] label [19, -9]
}

component legitimacy [0.88, 0.49] label [-80, -4]

component effect [0.47, 0.65] label [-56, -32]
pipeline effect {
  component unintended [0.34] label [-58, -17]
  component coerce [0.53] label [-38, 24]
  component hearts and minds [0.6] label [-23, 31]
  component deter [0.62] label [23, 44]
  component kinetic [0.68] label [18, 3]
}
component statecraft [0.82, 0.42] label [-42, -11]

component consequences [0.36, 0.65] label [-6, -13]
pipeline consequences {
  component deniability [0.43] label [-92, 3]
  component friendly fire [0.53] label [26, 32]
  component attribution [0.71] label [18, 2]
}

component awareness [0.12, 0.60] label [11, -6]
pipeline awareness {
  component digital awareness [0.38] label [-76, -19]
  component physical awareness [0.69] label [21, -14]
}
component accountability [0.42, 0.30] label [-111, 1]
component suprantional [0.98, 0.60] label [-98, -1]

component ethics [0.92, 0.39] label [-57, -2]

component others [0.83, 0.68] label [10, 3]

component people [0.89, 0.70] label [11, 4]

component treaties [0.92, 0.55] label [-71, 2]

suprantional -> government
government -> people
government -> "private / proxy"
suprantional -> ethics
government -> legitimacy
legitimacy -> statecraft
legitimacy -> sovereignty
sovereignty -> theatre
theatre -> effect
effect -> consequences
effect -> landscape
landscape -> awareness
ethics -> accountability
statecraft -> accountability
accountability -> attribution
"private / proxy" -> deniability
territory -> land
land -> kinetic
cyber -> electronic
cyber -> social media
social media -> culture
culture -> propaganda
economic -> finance
propaganda -> deter
coerce -> social media
social media -> hearts and minds
propaganda -> coerce
kinetic -> physical landscape
physical landscape -> physical awareness
finance -> supply chain
electronic -> supply chain
supply chain -> digital awareness
social media -> virtual landscape
ethics -> effect
"private / proxy" -> effect

statecraft -> sovereignty
suprantional -> treaties
treaties -> sovereignty
legitimacy -> legitimacy
legitimacy -> others
others -> hearts and minds
others -> competition
competition -> theatre

