wardley-beta

title healthcare - clinical trials management
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity / accepted

note "+indication" [0.66, 0.69]
component stakeholder [0.25, 0.68] label [9, 3]

component trial management [0.30, 0.42] label [-73, -28]
pipeline trial management {
  component CRO [0.43] label [13, -4]
}

component trial design [0.42, 0.43] label [-3, -15]
pipeline trial design {
  component umbrella [0.37] label [-33, 22]
  component basket [0.4] label [-36, -14]
  component platform [0.47] label [-34, 24]
  component Decentralised CT [0.55] label [-32, 13]
  component traditional [0.71] label [15, 5]
}
component report [0.70, 0.66] label [-52, 2]
component citizens [0.90, 0.69] label [12, -2]
component pharma [0.95, 0.62] label [-64, 3]
component government [0.95, 0.67] label [14, 0]
component drug [0.82, 0.65] label [-17, -13]
pipeline drug {
  component IP [0.44] label [-33, 1]
  component license [0.55] label [-58, -5]
  component biosimilars [0.57] label [-49, 20]
  component generic [0.69] label [14, 4]
  component health [0.7] label [14, 5]
}
component safety [0.74, 0.56] label [-56, 5]
component clinical research [0.55, 0.35] label [-47, -39]
pipeline clinical research {
  component digital simulation [0.2] label [-76, -3]
  component discovery [0.29] label [-31, 22]
  component licensing trials [0.4] label [19, -11]
}
component randomisation [0.57, 0.67] label [10, 2]
component scope [0.67, 0.68] label [8, -4]
component FDA [0.73, 0.66] label [-18, -10]
component sample [0.25, 0.60] label [-43, -8]
component costs [0.15, 0.67] label [-3, -12]
pipeline costs {
  component analysis [0.52] label [-33, 27]
  component management [0.7] label [17, 6]
}
component candidates [0.68, 0.32] label [-83, -4]
component protocol doc [0.64, 0.67] label [-93, -5]
component funding [0.06, 0.70] label [7, -8]
pipeline funding {
  component private [0.65] label [-66, 5]
  component public [0.73] label [17, 3]
}
component selection [0.21, 0.43] label [-75, -4]
pipeline selection {
  component site [0.38] label [-44, 4]
  component participant [0.45] label [16, 5]
}
component clinical liability [0.62, 0.69] label [7, -12]
component clinical systems [0.09, 0.39] label [-25, 10]
component data collection [0.04, 0.31] label [-62, -7]

government -> citizens
citizens -> health
health -> drug
pharma -> drug
drug -> safety
clinical research -> stakeholder
drug -> scope
safety -> FDA
pharma -> license
license -> FDA
license -> IP
trial -> scale
randomisation -> sample
sample -> costs
IP -> candidates
trial -> protocol doc
funding -> costs
safety -> clinical liability
clinical research -> clinical liability
candidates -> digital simulation
sample -> selection
costs -> clinical systems
selection -> clinical systems
stakeholder -> clinical systems
digital simulation -> data collection
clinical systems -> data collection
discovery -> data collection
biosimilars -> license
candidates -> discovery
scope -> protocol doc
scope -> report
protocol doc -> randomisation

FDA -> report
protocol doc -> clinical research
clinical research -> trial design
trial design -> trial management
CRO -> sample

