wardley-beta

title The JEWELED NET (BOOK CONCEPT), Oct 2023
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

note "For inspiring witches and magicians and those into self actualisation" [1.01, 0.32]

component Self [0.90, 0.58]

component GROWTH [0.80, 0.64] label [-13, -14]
pipeline GROWTH {
  component AUTHORITY [0.58] label [-82, 3]
  component CRAFT [0.68] label [0, -18]
  component money [0.72] label [18, 2]
}

component DISPOSITIONAL ATTITUDES [0.56, 0.62] label [-83, -32]
pipeline DISPOSITIONAL ATTITUDES {
  component moral imperative [0.68] label [22, -19]
}
note "How to a better human" [0.57, 0.63]

component CONTEXT [0.31, 0.40] label [-59, -14]
pipeline CONTEXT {
  component change [0.2] label [-67, 1]
  component status quo [0.45] label [4, -20]
}

component awareness [0.38, 0.42] label [-82, -6]

component VALUE JUDGEMENT [0.31, 0.56] label [-28, -38]
pipeline VALUE JUDGEMENT {
  component good for WE [0.51] label [-56, 26]
  component good for ME [0.58] label [22, 1]
}

component BELIEFS [0.19, 0.55] label [-64, -11]

component collective [0.94, 0.48] label [-57, -15]

component CAPABILITY FOR GROWTH [0.68, 0.66] label [1, -45]
pipeline CAPABILITY FOR GROWTH {
  component social factors [0.66] label [-25, 26]
  component education [0.7] label [18, 0]
}

component TRADITION [0.09, 0.62] label [4, -11]
pipeline TRADITION {
  component rituals [0.56] label [-71, 2]
  component stories [0.61] label [-37, 25]
  component symbols [0.64] label [17, 2]
}

component FUNDAMENTALS [0.48, 0.61] label [-8, -14]
pipeline FUNDAMENTALS {
  component spiritual Wisdom [0.64] label [-38, 17]
  component purpose [0.67] label [-5, 29]
  component passion [0.69] label [19, 9]
}

component individual experiences [0.12, 0.50] label [-80, -5]

self -> growth
BELIEFS -> VALUE JUDGEMENT
GROWTH -> VALUE JUDGEMENT
GROWTH -> DISPOSITIONAL ATTITUDES
GROWTH -> awareness
awareness -> context
Self -> GROWTH
collective -> BELIEFS
Self -> collective
BELIEFS -> ION
CAPABILITY FOR GROWTH -> GROWTH
CONTEXT -> awareness
moral imperative -> purpose
passion -> moral imperative
FUNDAMENTALS -> BELIEFS
FUNDAMENTALS -> awareness
DISPOSITIONAL ATTITUDES -> FUNDAMENTALS
BELIEFS -> TRADITION
BELIEFS -> individual experiences

