wardley-beta

title Conflict from the perspective of citizens, Oct 2023
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component Citizen [0.97, 0.66] label [4, -5]

component collective [0.89, 0.68] label [11, 2]

component space [0.71, 0.68] label [20, -3]
pipeline space {
  component psychological [0.35] label [-116, 1]
  component cultural [0.44] label [-69, -21]
  component technological [0.48] label [-60, 24]
  component political [0.52] label [-61, -19]
  component economic [0.55] label [-29, 25]
  component virtual [0.59] label [19, -19]
  component territorial [0.72] label [18, 3]
}

note "how we operate" [0.61, 0.36]
note "what we believe / value" [0.44, 0.33]

component beliefs [0.49, 0.57] label [-38, -15]
pipeline beliefs {
  component opinions [0.23] label [-65, -1]
  component hypothesis [0.26] label [-57, 24]
  component laws [0.62] label [-26, -19]
  component core values [0.65] label [-32, 24]
  component international laws [0.68] label [-45, -45]
  component universal beliefs [0.7] label [22, -18]
}

component principles [0.60, 0.55] label [-85, -7]
pipeline principles {
  component experiment [0.32] label [-90, -1]
  component practice [0.53] label [-24, 28]
  component universally accepted principles [0.68] label [26, -26]
}

component Collective memory [0.25, 0.69] label [-16, -45]
pipeline Collective memory {
  component symbols [0.64] label [-64, 14]
  component rituals [0.66] label [-48, -21]
  component heroes [0.68] label [-37, 31]
  component events [0.7] label [-4, 25]
  component stories [0.71] label [19, 4]
}

component identity [0.85, 0.65] label [10, 6]

component behaviour [0.83, 0.58] label [-75, 4]
component safety [0.94, 0.58] label [-58, -7]

component power [0.91, 0.62] label [9, -8]

collective -> Citizen

Collective memory -> beliefs
identity -> beliefs
identity -> Collective memory
identity -> space
collective -> behaviour
Citizen -> safety
safety -> behaviour
power -> safety
collective -> power
behaviour -> identity
collective -> space
identity -> collective
behaviour -> beliefs
principles -> behaviour

hypothesis -> experiment

