wardley-beta
title Dutch Housing
size [1100, 800]

component "user" [0.97, 0.57]
pipeline "user" {
  component "tomorrow's" [0.35]
  component "today" [0.68]
}
component "need for property" [0.84, 0.63]
component "sustainability" [0.83, 0.33]
evolve "tomorrow's" 0.68
evolve "sustainability" 0.5
component "increase property supply" [0.69, 0.64]
pipeline "increase property supply" {
  component "matrix like cavern" [0.22]
  component "retrofit" [0.6]
  component "refurbish" [0.65]
  component "new build" [0.69]
}
component "land" [0.55, 0.72]
component "existing housing stock" [0.52, 0.59]
component "out of control AI" [0.44, 0.13]
component "survey" [0.43, 0.61]
component "building materials" [0.21, 0.64]
pipeline "building materials" {
  component "prefab" [0.49]
  component "discrete materials" [0.68]
}
component "architectural design" [0.36, 0.55]
pipeline "architectural design" {
  component "bespoke" [0.37]
  component "standardised, eco friendly" [0.71]
}
component "carbon cost" [0.10, 0.53]
component "awareness of supply chain" [0.06, 0.30]
component "supply chain" [0.03, 0.69]

note "NOT" [0.82, 0.26]

"increase property supply" -> "need for property"
"new build" -> "land"
"retrofit" -> "existing housing stock"
"existing housing stock" -> "refurbish"
"matrix like cavern" -> "out of control AI"
"existing housing stock" -> "survey"
"new build" -> "building materials"
"new build" -> "standardised, eco friendly"
"standardised, eco friendly" -> "prefab"
"retrofit" -> "bespoke"
"refurbish" -> "bespoke"
"bespoke" -> "discrete materials"
"discrete materials" -> "carbon cost"
"prefab" -> "carbon cost"
"existing housing stock" -> "carbon cost"
"standardised, eco friendly" -> "carbon cost"
"need for property" -> "today"
"tomorrow's" -> "need for property"
"tomorrow's" -> "sustainability"
"sustainability" -> "carbon cost"
"carbon cost" -> "awareness of supply chain"
"awareness of supply chain" -> "supply chain"

