wardley-beta

title Energy - SMNR
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity / accepted

note "$1M / km air, 10x underground" [0.28, 0.25]
note ">110kV" [0.32, 0.39]
note "<110kV" [0.36, 0.61]
note "(+ SMNR)" [0.39, 0.52]
evolve sustainability 0.5
component awareness [0.48, 0.31] label [-70, 4]
component supply chain [0.40, 0.48] label [-101, 4]
component sovereignty [0.93, 0.59] label [-73, -12]
pipeline sovereignty {
  component economic [0.45] label [-82, 2]
  component CNI [0.56] label [-27, 23]
  component government [0.68] label [-82, 0]
  component society [0.71] label [11, 0]
  component territorial [0.73] label [13, 3]
}

component user [0.85, 0.68] label [-37, -8]
pipeline user {
  component tomorrow [0.42] label [-75, 3]
  component today [0.72] label [18, 5]
}
evolve tomorrow 0.59
component cost [0.70, 0.63] label [-4, -11]
pipeline cost {
  component externality [0.42] label [-91, 14]
  component price [0.69] label [16, 3]
}
component capital [0.06, 0.72] label [4, 4]
component protection system [0.04, 0.27] label [-75, -18]

component reserve [0.02, 0.70] label [9, 4]

component distribution [0.35, 0.63] label [-93, 11]
component landscape [0.12, 0.25] label [-76, 2]

component energy usage [0.58, 0.65] label [10, 6]
component energy mix [0.43, 0.67] label [12, -5]
pipeline energy mix {
  component renewable [0.58] label [-81, 2]
  component fossil [0.73] label [17, 4]
}

note "(grid)" [0.37, 0.42]

component energy production [0.13, 0.68] label [-22, -38]
pipeline energy production {
  component nuclear [0.38] label [-69, 5]
  component solar collectors [0.41] label [-55, -47]
  component gas [0.44] label [-11, -19]
  component SMNR [0.51] label [-26, -15]
  component solar microgen [0.74] label [17, 4]
}
component energy generation [0.51, 0.65] label [-56, -36]
pipeline energy generation {
  component OTC market [0.59] label [-75, -16]
  component spotmarket [0.7] label [-21, -17]
  component public good [0.78] label [16, 4]
}

component SMNR supply chain [0.03, 0.38] label [-63, -24]

component storage [0.25, 0.56] label [-68, -4]
pipeline storage {
  component synthetic [0.2] label [-79, 2]
  component transmission [0.41] label [-97, 0]
  component hydrogen [0.41] label [4, 21]
  component potential energy [0.53] label [-49, 13]
  component battery [0.7] label [15, 7]
}
component survivability [0.77, 0.55] label [-99, -4]
pipeline survivability {
  component sustainability [0.43] label [-113, -1]
  component security [0.68] label [17, 3]
}
component education [0.72, 0.35] label [-81, 2]
note "(people)" [0.80, 0.73]
component CO2 [0.59, 0.38] label [-36, 5]

component control [0.63, 0.64] label [-63, -7]
pipeline control {
  component regulation [0.6] label [-89, 5]
  component "market" [0.69] label [19, 4]
}

evolve transmission 0.52
evolve distribution 0.75
note "+constraint" [0.31, 0.66]
evolve awareness 0.4
evolve SMNR 0.6

society -> consumers
consumers -> behaviour
society -> survival
mkt_competition -> energy usage
education -> efficiency
behaviour -> expectations
political -> expectations
energy usage -> energy generation
energy generation -> energy mix
renewable -> storage
energy mix -> energy production
efficiency -> energy usage
eco luddites -> expectations
expectations -> history
generators -> energy usage
government -> society
government -> political
mkt_competition -> "other"
energy generation -> supply chain
regulation -> awareness
awareness -> awareness
supply chain -> awareness
encumbents -> energy usage
consumers -> mkt_competition
providers -> mkt_competition
sustainability -> education
sustainability -> renewable
tomorrow -> sustainability
sustainability -> externality
user -> behaviour
behaviour -> cost
price -> "market"
externality -> regulation
today -> security
security -> price
security -> energy usage
user -> survivability
survivability -> cost
survivability -> control
energy mix -> transmission
transmission -> protection system
energy production -> capital
capital -> transmission
capital -> storage
distribution -> energy mix
supply chain -> transmission
supply chain -> distribution
distribution -> capital
transmission -> landscape
reserve -> gas
externality -> CO2
CO2 -> energy mix
today -> society
sovereignty -> government
CNI -> security

SMNR -> SMNR supply chain
economic -> SMNR supply chain

