wardley-beta
title Intuitive Finance, Investor, Dec 2023
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity / accepted

component investors [1.00, 0.68] label [-5, -12]

component risk profile [0.86, 0.40] label [-33, -21]
pipeline risk profile {
  component risk appetite [0.39] label [-114, 3]
  component "market risk" [0.42] label [-67, 24]
  component strategy [0.46] label [-8, 24]
  component domain expertise [0.57] label [-34, -47]
  component brand [0.69] label [-25, 20]
  component capital [0.71] label [19, 1]
}

component industry [0.20, 0.66] label [15, 3]

component prediction score [0.95, 0.58] label [-74, -30]

component investment type [0.63, 0.68] label [-7, -39]
pipeline investment type {
  component derivatives [0.58] label [-98, 2]
  component treasury bonds [0.62] label [-81, -23]
  component stock [0.64] label [-21, 23]
  component real estates [0.68] label [-6, 23]
  component cash [0.71] label [19, 3]
}

component investment criteria checklist [0.40, 0.40] label [-43, -57]
pipeline investment criteria checklist {
  component business strategy [0.22] label [-49, 15]
  component executive brand [0.24] label [-20, -44]
  component bias [0.38] label [-12, 28]
  component "need / product analysis" [0.51] label [-48, -74]
  component emotional attachment [0.53] label [-10, 12]
  component circle of competence [0.57] label [-34, -64]
  component "market analysis" [0.65] label [-9, 14]
  component finances [0.69] label [-33, -25]
}

component luck [0.94, 0.69] label [8, 5]
component assets [0.94, 0.67] label [-41, 15]

investors -> prediction score
prediction score -> risk profile
prediction score -> investment type
investment type -> investment criteria checklist
industry -> domain expertise
circle of competence -> industry
luck -> investors
assets -> investors

