wardley-beta

title defence - multi domain
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component government [0.96, 0.65] label [-29, -9]
component society [0.93, 0.68] label [7, -5]
component citizen [0.90, 0.71] label [8, 3]

component legitimacy [0.92, 0.58] label [-84, -2]

component sovereignty [0.71, 0.69] label [-3, -11]
pipeline sovereignty {
  component digital [0.46] label [-71, 3]
  component economic [0.53] label [-30, 25]
  component political [0.61] label [-45, 26]
  component cultural [0.67] label [-21, 24]
  component physical [0.75] label [17, 7]
}

component theatre [0.58, 0.62] label [-43, -10]
pipeline theatre {
  component sanctions [0.4] label [-87, 8]
  component critical national infrastructure [0.66] label [-68, 27]
  component land [0.73] label [12, -14]
}

component landscape [0.25, 0.55] label [-73, -9]
pipeline landscape {
  component territory [0.38] label [-89, 1]
  component supply chain [0.63] label [19, 7]
}

component situational awareness [0.10, 0.60] label [-74, -25]
pipeline situational awareness {
  component economic awareness [0.31] label [-79, -19]
  component digital awareness [0.39] label [-45, 27]
  component physical awareness [0.69] label [15, -5]
}

component success [0.83, 0.70] label [8, 1]
component appearance of success [0.84, 0.64] label [-64, -21]

component CNI [0.42, 0.65] label [-29, -6]
pipeline CNI {
  component telecoms [0.6] label [-75, 5]
  component finance [0.63] label [-21, 28]
  component energy [0.71] label [-32, -25]
  component water [0.73] label [-9, -17]
  component food [0.76] label [24, 6]
}

government -> society
society -> citizen
government -> legitimacy
society -> success
citizen -> belonging
belonging -> trust
legitimacy -> trust
competence -> success
belonging -> benevolence
society -> norms
norms -> integrity
legitimacy -> sovereignty
success -> physical
success -> economic
digital -> success
integrity -> political
integrity -> cultural
cultural -> benevolence
physical -> land
physical -> sea
sovereignty -> theatre
physical -> air
physical -> space
cultural -> art
digital -> cyber
economic -> economy
political -> cyber
belonging -> appearance of success
appearance of success -> political
appearance of success -> critical national infrastructure
critical national infrastructure -> CNI
land -> territory
air -> territory
cyber -> telecoms
space -> telecoms
economy -> telecoms
telecoms -> supply chain
energy -> supply chain
water -> supply chain
food -> supply chain
economy -> supply chain
supply chain -> economic awareness
territory -> physical awareness
theatre -> situational awareness
supply chain -> digital awareness
theatre -> capability
theatre -> operating model
capability -> capability
capability -> supply chain
landscape -> situational awareness
theatre -> landscape
economy -> finance
citizen -> appearance of success
economic -> sanctions
sanctions -> supply chain
sanctions -> finance
appearance of success -> cultural

