wardley-beta
title twitter
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component user [0.98, 0.70]
component twitter [0.98, 0.52]
component advertisers [0.98, 0.66]
component regulators [0.98, 0.58]
component device [0.95, 0.72]

component adverts [0.96, 0.68]

