wardley-beta

title transportation - Coherent City, Dec 2022
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component people [0.97, 0.71]
component government [0.99, 0.48]
component CITY FUNCTIONS [0.77, 0.56]
pipeline CITY FUNCTIONS {
  component dwellings [0.37]
  component shops [0.41]
  component restaurants [0.45]
  component police station [0.52]
  component banks [0.61]
  component "factories w'hses" [0.65]
}
component SOCIAL PRACTICES [0.88, 0.66]
pipeline SOCIAL PRACTICES {
  component virtual practices [0.36]
  component physical practices [0.76]
}
component SPACE [0.68, 0.57]
pipeline SPACE {
  component physical [0.45]
  component virtual [0.72]
}
component WAYS [0.60, 0.48]
pipeline WAYS {
  component paths [0.37]
  component waterways [0.42]
  component "signals/signs" [0.48]
  component roads [0.53]
  component rail [0.58]
  component pipes [0.64]
  component cables [0.71]
  component air [0.74]
}
component territory [0.72, 0.25]
component "construction/maintenance" [0.53, 0.40]
component decarbonisation [0.69, 0.19]
component TRANSPORT SCHEMES [0.19, 0.42]
pipeline TRANSPORT SCHEMES {
  component rapid bus [0.37]
  component bike share [0.42]
  component congestion charge [0.46]
  component "15 minute city" [0.49]
  component parking [0.53]
}
component enforcement [0.29, 0.49]
component MODE [0.45, 0.68]
pipeline MODE {
  component autonomous vehicles [0.47]
  component drones [0.57]
  component "e-scooters" [0.61]
  component planes [0.68]
  component automobiles [0.7]
  component trains [0.73]
  component internet access [0.75]
  component cycle [0.77]
  component walk [0.79]
}
component functional transport system [0.51, 0.28]
component obstruction removal [0.51, 0.54]
component Transport Planning [0.38, 0.35]
component TRANSPORT INFORMATION [0.11, 0.34]
pipeline TRANSPORT INFORMATION {
  component digital twin [0.23]
  component historical [0.46]
}
component regulation [0.31, 0.42]
component decision making [0.32, 0.37]
component Transport Policy [0.30, 0.28]
component stable climate [0.85, 0.23]
component sensors [0.03, 0.52]
component surveys [0.03, 0.42]
component data analysis [0.03, 0.30]
component AWARENESS [0.26, 0.37]

component traffic management [0.44, 0.27]

component FUEL [0.19, 0.75]
pipeline FUEL {
  component hydrogen [0.63]
  component electricity [0.71]
  component petroleum [0.78]
  component animal power [0.87]
}

component ENERGY INPUT MIX [0.06, 0.73]
pipeline ENERGY INPUT MIX {
  component nuclear [0.65]
  component renewable [0.69]
  component fossil [0.75]
}
component HUBS [0.36, 0.58]
pipeline HUBS {
  component local mobility hubs [0.48]
  component ISPs [0.54]
  component integrated transport station [0.59]
  component car parks [0.65]
  component fuel stations [0.69]
}

government -> people
goods -> CITY FUNCTIONS
services -> CITY FUNCTIONS
"safety & security" -> CITY FUNCTIONS
CITY FUNCTIONS -> SPACE
CITY FUNCTIONS -> WAYS
physical -> territory
WAYS -> "construction/maintenance"
people -> MODE
goods -> MODE
CITY FUNCTIONS -> MODE
MODE -> WAYS
WAYS -> obstruction removal
WAYS -> "signals/signs"
government -> functional transport system
people -> functional transport system
functional transport system -> WAYS
functional transport system -> MODE
functional transport system -> Transport Planning
Transport Planning -> TRANSPORT INFORMATION
Transport Planning -> enforcement
Transport Planning -> regulation
Transport Planning -> decision making
Transport Planning -> Transport Policy
government -> stable climate
people -> stable climate
TRANSPORT INFORMATION -> data analysis
TRANSPORT INFORMATION -> surveys
TRANSPORT INFORMATION -> sensors
"food & water" -> stable climate
animal power -> "food & water"
MODE -> FUEL
government -> territory
WAYS -> HUBS
MODE -> HUBS
functional transport system -> HUBS
people -> CITY FUNCTIONS
WAYS -> SPACE
stable climate -> decarbonisation
Transport Policy -> TRANSPORT SCHEMES
decarbonisation -> Transport Policy

physical practices -> physical
virtual -> virtual practices
SOCIAL PRACTICES -> people
virtual -> air
virtual -> cables
cables -> internet access
air -> internet access
Transport Policy -> AWARENESS
WAYS -> AWARENESS
decarbonisation -> FUEL
AWARENESS -> TRANSPORT INFORMATION
AWARENESS -> FUEL
electricity -> ENERGY INPUT MIX
hydrogen -> ENERGY INPUT MIX
functional transport system -> traffic management
traffic management -> AWARENESS
fuel stations -> FUEL

