wardley-beta
title defence - general
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component government [0.96, 0.65] label [-29, -9]
component society [0.94, 0.67] label [11, 2]
component citizen [0.90, 0.71] label [8, 3]

component legitimacy [0.92, 0.58] label [-84, -2]
component trust [0.74, 0.55] label [-42, -3]
pipeline trust {
  component benevolence [0.42] label [-97, 4]
  component competence [0.5] label [-67, 45]
  component integrity [0.57] label [26, 4]
}
component belonging [0.83, 0.64] label [18, 4]
component norms [0.90, 0.63] label [12, 9]
component success [0.65, 0.73] label [7, 3]
component appearance of success [0.74, 0.73] label [8, -22]
component sovereignty [0.58, 0.69] label [0, -12]
pipeline sovereignty {
  component digital [0.46] label [-71, 3]
  component economic [0.53] label [-24, 28]
  component political [0.62] label [-45, 24]
  component cultural [0.67] label [1, 47]
  component physical [0.75] label [17, 7]
}

component theatre [0.41, 0.63] label [-43, -10]
pipeline theatre {
  component economy [0.34] label [-46, 31]
  component space [0.48] label [-15, 28]
  component cyber [0.53] label [-20, 75]
  component art [0.57] label [-9, 28]
  component critical national infrastructure [0.66] label [-45, 24]
  component air [0.69] label [-15, -20]
  component sea [0.71] label [-10, 41]
  component land [0.73] label [15, 5]
}
component landscape [0.09, 0.56] label [-73, -9]
pipeline landscape {
  component supply chain [0.38] label [-110, 6]
  component territory [0.7] label [18, 2]
}

component CNI [0.24, 0.65] label [-29, -6]
pipeline CNI {
  component telecoms [0.6] label [-78, 4]
  component energy [0.66] label [-18, 42]
  component food [0.72] label [20, 7]
}

government -> society
society -> citizen
government -> legitimacy
society -> success
citizen -> belonging
legitimacy -> trust
competence -> success
belonging -> benevolence
society -> norms
norms -> integrity
legitimacy -> sovereignty
success -> physical
success -> economic
digital -> success
integrity -> political
integrity -> cultural
cultural -> benevolence
physical -> land
physical -> sea
physical -> air
physical -> space
cultural -> art
digital -> cyber
economic -> economy
political -> cyber
belonging -> appearance of success
appearance of success -> political
appearance of success -> critical national infrastructure
critical national infrastructure -> CNI
land -> territory
air -> territory
cyber -> telecoms
space -> telecoms
economy -> telecoms
telecoms -> supply chain
energy -> supply chain
water -> supply chain
food -> supply chain
economy -> supply chain
supply chain -> economic awareness
territory -> physical awareness
supply chain -> digital awareness
theatre -> capability
theatre -> operating model
capability -> capability
capability -> supply chain
landscape -> situational awareness
economy -> finance
cyber -> supply chain

