wardley-beta
title defence - general
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component "government" [0.96, 0.65]
component "society" [0.94, 0.67]
component "citizen" [0.90, 0.71]

component "legitimacy" [0.92, 0.58]
component "trust" [0.74, 0.55]
pipeline "trust" {
  component "benevolence" [0.42]
  component "competence" [0.5]
  component "integrity" [0.57]
}
component "belonging" [0.83, 0.64]
component "norms" [0.90, 0.63]
component "success" [0.65, 0.73]
component "appearance of success" [0.74, 0.73]
component "sovereignty" [0.58, 0.69]
pipeline "sovereignty" {
  component "digital" [0.46]
  component "economic" [0.53]
  component "political" [0.62]
  component "cultural" [0.67]
  component "physical" [0.75]
}

component "theatre" [0.41, 0.63]
pipeline "theatre" {
  component "economy" [0.34]
  component "space" [0.48]
  component "cyber" [0.53]
  component "art" [0.57]
  component "critical national infrastructure" [0.66]
  component "air" [0.69]
  component "sea" [0.71]
  component "land" [0.73]
}
component "landscape" [0.09, 0.56]
pipeline "landscape" {
  component "supply chain" [0.38]
  component "territory" [0.7]
}

component "CNI" [0.24, 0.65]
pipeline "CNI" {
  component "telecoms" [0.6]
  component "energy" [0.66]
  component "food" [0.72]
}

"government" -> "society"
"society" -> "citizen"
"government" -> "legitimacy"
"society" -> "success"
"citizen" -> "belonging"
"legitimacy" -> "trust"
"competence" -> "success"
"belonging" -> "benevolence"
"society" -> "norms"
"norms" -> "integrity"
"legitimacy" -> "sovereignty"
"success" -> "physical"
"success" -> "economic"
"digital" -> "success"
"integrity" -> "political"
"integrity" -> "cultural"
"cultural" -> "benevolence"
"physical" -> "land"
"physical" -> "sea"
"physical" -> "air"
"physical" -> "space"
"cultural" -> "art"
"digital" -> "cyber"
"economic" -> "economy"
"political" -> "cyber"
"belonging" -> "appearance of success"
"appearance of success" -> "political"
"appearance of success" -> "critical national infrastructure"
"critical national infrastructure" -> "CNI"
"land" -> "territory"
"air" -> "territory"
"cyber" -> "telecoms"
"space" -> "telecoms"
"economy" -> "telecoms"
"telecoms" -> "supply chain"
"energy" -> "supply chain"
"water" -> "supply chain"
"food" -> "supply chain"
"economy" -> "supply chain"
"supply chain" -> "economic awareness"
"territory" -> "physical awareness"
"supply chain" -> "digital awareness"
"theatre" -> "capability"
"theatre" -> "operating model"
"capability" -> "capability"
"capability" -> "supply chain"
"landscape" -> "situational awareness"
"economy" -> "finance"
"cyber" -> "supply chain"

