wardley-beta
title defence - multi domain - operating model
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component theatre [0.84, 0.62] label [-55, -4]
pipeline theatre {
  component economy [0.33] label [-68, 5]
  component space [0.43] label [-15, 28]
  component cyber [0.48] label [-15, 60]
  component air [0.71] label [-21, 24]
  component sea [0.73] label [-9, 28]
  component land [0.75] label [20, 5]
}
component operating model [0.72, 0.54] label [-58, -29]
pipeline operating model {
  component decentralised [0.41] label [-51, -19]
  component asynchronous [0.42] label [-53, 24]
  component synchronous [0.68] label [-58, 31]
  component centralised [0.69] label [-51, -21]
}

component sovereignty [0.98, 0.68] label [-33, 60]
pipeline sovereignty {
  component digital [0.46] label [-71, 3]
  component economic [0.53] label [-21, 58]
  component political [0.62] label [-45, 24]
  component cultural [0.7] label [-24, 42]
  component physical [0.75] label [17, 7]
}

component doctrine [0.44, 0.63] label [-72, -3]
pipeline doctrine {
  component Agile [0.45] label [-37, 24]
  component SOP [0.69] label [-14, 24]
}

component resources [0.55, 0.53] label [-2, -19]
pipeline resources {
  component tech superiority [0.5] label [-84, -17]
  component volume operations [0.72] label [-50, -45]
}
component delivery [0.24, 0.63] label [-32, -9]
pipeline delivery {
  component big ticket [0.44] label [-87, 5]
  component modern tanks [0.53] label [-59, -19]
  component Light vehicles [0.63] label [-19, 27]
  component drones [0.71] label [20, 4]
}

component awareness of landscape [0.09, 0.56] label [-70, -42]
pipeline awareness of landscape {
  component supply chain [0.3] label [-108, 1]
  component territory [0.74] label [20, -6]
}

operating model -> composition
composition -> resources
PMC -> profit
operating model -> doctrine
operating model -> weapon
volume operations -> drones
tech superiority -> modern tanks
tech superiority -> big ticket
Agile -> Light vehicles
Agile -> drones
SOP -> modern tanks
SOP -> big ticket
SOP -> hiearachy
freedom -> Agile
decentralised -> Agile
centralised -> SOP
lived experience -> culture
territorial -> kinetic
economic -> cyber
corporate -> PMC
military -> public
centralised -> hiearachy
operating model -> operating environment
physical -> land
physical -> sea
physical -> air
physical -> space
digital -> cyber
economic -> economy
belonging -> appearance of success
appearance of success -> political
appearance of success -> critical national infrastructure
critical national infrastructure -> CNI
land -> territory
cyber -> telecoms
space -> telecoms
economy -> telecoms
supply chain -> economic awareness
territory -> physical awareness
theatre -> situational awareness
supply chain -> digital awareness
theatre -> capability
theatre -> operating model
landscape -> situational awareness
military -> conscripts
military -> professional
operating model -> culture
professional -> investment
operating model -> operating model
resources -> operating model
economy -> supply chain
supply chain -> cyber
delivery -> supply chain
delivery -> territory

