wardley-beta
title Finance - Sovereign risks
size [1100, 800]

evolution genesis / concept -> custom / emerging -> product / converging -> commodity/ accepted

note "+ SWIFT is about perceived success" [0.07, 0.01]
note "+ Leading to bifurcation of finances" [0.04, 0.01]
note "+ Does the black market have a better understanding of its supply chain?" [0.01, 0.01]

component legal [0.08, 0.59] label [6, -8]
pipeline legal {
  component principle [0.51] label [-83, 5]
  component rule based [0.67] label [38, 3]
  component physical awareness [0.69] label [19, -10]
}
component government [0.96, 0.59] label [19, 0]
pipeline government {
  component insurgent [0.54] label [-84, 1]
  component incumbent [0.63] label [16, 6]
}
component society [0.88, 0.64] label [12, 2]
component public [0.84, 0.68] label [10, -5]
component legitimacy [0.87, 0.55] label [-81, -4]
component sovereign risk [0.72, 0.62] label [-60, -20]
pipeline sovereign risk {
  component economic [0.48] label [-71, 3]
  component cultural [0.54] label [-65, -15]
  component political [0.58] label [24, -16]
  component CNI [0.65] label [1, 31]
  component territorial [0.69] label [17, 3]
  component perceived success [0.69] label [22, -17]
}
component economic risk [0.48, 0.57] label [-19, -15]
pipeline economic risk {
  component capital access [0.45] label [-115, 2]
  component liquidity [0.53] label [-79, 39]
  component supply chains [0.6] label [-14, 31]
  component protocols [0.63] label [10, -17]
  component debt [0.65] label [-46, 46]
  component taxation [0.67] label [36, -16]
  component currency [0.7] label [15, 4]
}
component law [0.82, 0.41] label [-33, 0]
component norms [0.73, 0.36] label [-53, -1]
component belonging [0.81, 0.67] label [9, 2]
component success [0.82, 0.60] label [7, 4]
component CNI Risk [0.62, 0.66] label [14, -32]
pipeline CNI Risk {
  component smart cities [0.34] label [-72, -19]
  component finance [0.43] label [-26, -15]
  component history [0.52] label [23, 29]
  component telecom [0.62] label [-27, 31]
  component energy [0.68] label [-37, 30]
  component food [0.72] label [15, 4]
}

component awareness [0.15, 0.51] label [-21, -11]
pipeline awareness {
  component economic awareness [0.31] label [-106, -33]
  component "evolved" [0.41] label [-83, 31]
}

component sovereign action [0.22, 0.59] label [5, -26]
pipeline sovereign action {
  component sanctions [0.42] label [-26, 24]
}
component international trade [0.53, 0.38] label [-90, -9]
component "market" [0.37, 0.71] label [7, -5]
pipeline "market" {
  component black market [0.62] label [-102, 3]
  component free market [0.76] label [16, 6]
}

component risk [0.30, 0.66] label [10, -4]
pipeline risk {
  component personal [0.61] label [-71, 4]
  component limited liability [0.71] label [17, -6]
}

incumbent -> society
society -> public
incumbent -> legitimacy
legitimacy -> sovereign risk
economic -> economic risk
legitimacy -> law
law -> sovereign risk
society -> norms
law -> norms
society -> success
norms -> success
public -> belonging
belonging -> norms
belonging -> perceived success
perceived success -> CNI
success -> economic
CNI -> CNI Risk
perceived success -> history
cultural -> history
insurgent -> legitimacy
insurgent -> history
insurgent -> perceived success
CNI Risk -> supply chains
territorial -> physical awareness
supply chains -> digital awareness
finance -> economic awareness
economic risk -> awareness
finance -> debt
sovereign risk -> sovereign action
sanctions -> economic awareness
finance -> capital access
law -> legal
norms -> principle

finance -> international trade
international trade -> rule based
international trade -> economic risk
supply chains -> economic awareness
economic awareness -> "evolved"
black market -> "evolved"
law -> personal
rule based -> limited liability
limited liability -> free market
black market -> personal
"market" -> risk
risk -> "market"

