wardley-beta
title Finance - AI - version 1.0
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity/ accepted

component client [0.97, 0.76] label [18, 6]
component manage budget [0.89, 0.75] label [13, 4]

component bad actors [0.97, 0.65] label [-84, 6]
component state [0.96, 0.71] label [-15, -16]
component CNI [0.93, 0.45] label [-27, -12]

component CAPABILITIES [0.86, 0.47] label [-94, -9]
pipeline CAPABILITIES {
  component offence [0.44] label [-68, 3]
  component defence [0.51] label [19, 1]
}

component NARROW AI [0.20, 0.69] label [3, -11]
pipeline NARROW AI {
  component LLM [0.56] label [-9, 24]
  component NLP [0.59] label [-9, 28]
  component localization [0.62] label [2, 44]
  component anomaly detection [0.65] label [-28, 29]
}

evolve open banking API 0.71

component BANKING SERVICES [0.78, 0.73] label [6, -33]
pipeline BANKING SERVICES {
  component payment [0.7] label [-68, -1]
  component loans [0.75] label [-15, 28]
  component savings [0.78] label [21, 4]
}

component ACCESS [0.65, 0.72] label [-54, -19]
pipeline ACCESS {
  component "3rd party tools" [0.46] label [-75, -29]
  component chatbots [0.62] label [-66, -51]
  component internet banking [0.69] label [-15, 24]
  component telebanking [0.72] label [19, 43]
  component ATM [0.74] label [-12, -19]
  component bank teller [0.77] label [16, 1]
}

component IDENTITY [0.55, 0.42] label [-67, -9]
pipeline IDENTITY {
  component fraud detection [0.52] label [-45, -45]
  component authentification [0.57] label [45, -9]
}

component CERTIFYING AUTHORITY [0.42, 0.66] label [7, -36]
pipeline CERTIFYING AUTHORITY {
  component bank [0.62] label [-37, 31]
  component web giants [0.67] label [-20, 30]
  component gov bodies [0.7] label [18, -1]
}

component BANK PRESENTATION [0.28, 0.47] label [-66, -37]
pipeline BANK PRESENTATION {
  component robobanking [0.36] label [-102, -1]
  component bank API [0.4] label [-25, 31]
  component open banking API [0.5] label [5, -47]
}

component CORE BANKING SYSTEMS [0.06, 0.45] label [-1, -18]
pipeline CORE BANKING SYSTEMS {
  component Semantic APIs [0.37] label [-79, -22]
  component training dataset [0.62] label [-73, 26]
}

evolve NARROW AI 0.76

client -> manage budget
manage budget -> BANKING SERVICES
ACCESS -> BANKING SERVICES
CORE BANKING SYSTEMS -> BANK PRESENTATION
BANK PRESENTATION -> ACCESS
ACCESS -> IDENTITY
authentification -> CERTIFYING AUTHORITY
bad actors -> authentification
bad actors -> CERTIFYING AUTHORITY
bad actors -> NARROW AI
state -> CNI
CNI -> BANKING SERVICES
CNI -> CAPABILITIES
defence -> NARROW AI
fraud detection -> NARROW AI
NARROW AI -> chatbots
robobanking -> NARROW AI
NARROW AI -> training dataset
open banking API -> "3rd party tools"

