wardley-beta
title Gaming Industry - Consumer Perspective, 2023 - CREATED BY CHATGPT4
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component Consumer [0.95, 0.74] label [2, -13]

component GAME PLATFORMS [0.8, 0.5] label [-58, -15]
pipeline GAME PLATFORMS {
  component Mobile Gaming [0.45] label [-113, -3]
  component Cloud Gaming [0.53] label [-18, 26]
  component Consoles [0.6] label [14, -17]
  component PC Gaming [0.71] label [25, 2]
}

component GAME TYPES [0.60, 0.61] label [-37, -14]
pipeline GAME TYPES {
  component Casual Games [0.51] label [-104, 2]
  component Indie Games [0.57] label [-57, 26]
  component Virtual Reality [0.64] label [-16, 28]
  component Esports [0.67] label [-7, 44]
  component AAA Titles [0.72] label [20, 4]
}

component MONETIZATION MODELS [0.48, 0.49] label [-95, -32]
pipeline MONETIZATION MODELS {
  component Ad-supported [0.37] label [-107, -1]
  component Microtransactions [0.43] label [-14, 25]
  component Subscription [0.56] label [-74, 44]
  component one-time fee [0.71] label [-11, 31]
}

component GAME COMMUNITIES [0.34, 0.56] label [-99, -13]
pipeline GAME COMMUNITIES {
  component Streaming Platforms [0.47] label [-92, -13]
  component Multiplayer Chats [0.61] label [28, -43]
  component Forums [0.69] label [22, 6]
}

component "HARDWARE & ACCESSORIES" [0.23, 0.65] label [11, -39]
pipeline "HARDWARE & ACCESSORIES" {
  component VR Headsets [0.59] label [-97, 4]
  component Gaming PCs [0.63] label [-5, 31]
  component Gamepads [0.69] label [25, 3]
}

component GAME CONTENT [0.12, 0.57] label [-90, -13]
pipeline GAME CONTENT {
  component Soundtrack [0.54] label [-99, 5]
  component Graphics [0.64] label [-33, 29]
  component Storyline [0.7] label [21, 3]
}

Consumer -> GAME PLATFORMS
Consumer -> GAME TYPES

GAME PLATFORMS -> "HARDWARE & ACCESSORIES"
GAME TYPES -> MONETIZATION MODELS
GAME COMMUNITIES -> GAME PLATFORMS
GAME COMMUNITIES -> GAME TYPES
GAME CONTENT -> GAME TYPES

