wardley-beta
title Gaming Industry - Consumer Perspective, 2023 - CREATED BY CHATGPT4
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component Consumer [0.95, 0.74]

component GAME PLATFORMS [0.8, 0.5]
pipeline GAME PLATFORMS {
  component Mobile Gaming [0.45]
  component Cloud Gaming [0.53]
  component Consoles [0.6]
  component PC Gaming [0.71]
}

component GAME TYPES [0.60, 0.61]
pipeline GAME TYPES {
  component Casual Games [0.51]
  component Indie Games [0.57]
  component Virtual Reality [0.64]
  component Esports [0.67]
  component AAA Titles [0.72]
}

component MONETIZATION MODELS [0.48, 0.49]
pipeline MONETIZATION MODELS {
  component "Ad-supported" [0.37]
  component Microtransactions [0.43]
  component Subscription [0.56]
  component "one-time fee" [0.71]
}

component GAME COMMUNITIES [0.34, 0.56]
pipeline GAME COMMUNITIES {
  component Streaming Platforms [0.47]
  component Multiplayer Chats [0.61]
  component Forums [0.69]
}

component "HARDWARE & ACCESSORIES" [0.23, 0.65]
pipeline "HARDWARE & ACCESSORIES" {
  component VR Headsets [0.59]
  component Gaming PCs [0.63]
  component Gamepads [0.69]
}

component GAME CONTENT [0.12, 0.57]
pipeline GAME CONTENT {
  component Soundtrack [0.54]
  component Graphics [0.64]
  component Storyline [0.7]
}

Consumer -> GAME PLATFORMS
Consumer -> GAME TYPES

GAME PLATFORMS -> "HARDWARE & ACCESSORIES"
GAME TYPES -> MONETIZATION MODELS
GAME COMMUNITIES -> GAME PLATFORMS
GAME COMMUNITIES -> GAME TYPES
GAME CONTENT -> GAME TYPES

