wardley-beta

title TELECOMS - Space - FEB 2023
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component corporation [0.99, 0.53] label [-87, 6]
component government [0.99, 0.60] label [24, 6]

component backhaul [0.50, 0.73] label [10, 5]
component USER TERMINAL [0.61, 0.72] label [13, 7]
component SATELLITE [0.73, 0.66] label [-72, -11]
pipeline SATELLITE {
  component GEO Sat [0.34] label [-69, 4]
  component LEO microsat [0.7] label [-2, -18]
  component launchers [0.72] label [22, 9]
}

component geography [0.66, 0.39] label [-74, 12]

component NETWORK ACCESS [0.90, 0.68] label [24, -23]
pipeline NETWORK ACCESS {
  component mesh network [0.47] label [-107, 0]
  component physical network [0.59] label [-57, -42]
  component consumer [0.67] label [1, -19]
  component broadcast [0.76] label [18, 5]
}

component TOPOLOGY [0.81, 0.66] label [11, -5]
pipeline TOPOLOGY {
  component fibre [0.35] label [-56, 3]
  component mobile [0.42] label [-6, 39]
  component NTN (non terrestrial Network) [0.73] label [36, -33]
}
component groundstation [0.53, 0.67] label [9, -1]

component SPECTRUM [0.33, 0.68] label [9, -6]
pipeline SPECTRUM {
  component V (40GHz) [0.67] label [-81, 3]
  component Ka (27GHz) [0.68] label [-5, 31]
  component Ku (12GHz) [0.7] label [16, 1]
}

component Optical Sat2Sat Coms [0.56, 0.40] label [-44, 12]
component PROPULSION [0.59, 0.66] label [-80, -3]
pipeline PROPULSION {
  component Xenon [0.59] label [-52, 4]
  component Krypton [0.67] label [15, 6]
}

component power [0.65, 0.72] label [11, 3]
component COOLING [0.67, 0.60] label [-121, 33]
pipeline COOLING {
  component Thermal Electric [0.51] label [-78, 37]
  component Cryogens [0.61] label [-40, 26]
  component Radiative [0.63] label [17, 4]
}

component CONTROL SYSTEMS [0.22, 0.55] label [13, -27]
pipeline CONTROL SYSTEMS {
  component fleet management [0.38] label [-84, -12]
  component debris tracking [0.46] label [-34, -43]
  component orbit tracking [0.69] label [19, 1]
}

component AUTOMATION [0.11, 0.61] label [14, 2]

component supply chains [0.02, 0.65] label [11, 1]

component beamforming [0.39, 0.67] label [-77, 18]
component ANTENNA [0.47, 0.68] label [4, -7]
pipeline ANTENNA {
  component beam_steering [0.65] label [-100, 15]
  component phased array antennas [0.67] label [-38, 31]
}

component supply chain awareness [0.05, 0.34] label [-66, -14]
fibre -> wire
"5G" -> masts
masts -> geography
wire -> geography
NETWORK ACCESS -> TOPOLOGY
physical network -> fibre
virtual practices -> virtual space
physical practices -> physical space
physical space -> geography

socialisation -> social
collaboration -> social
work -> collaboration
work -> socialisation
consumer -> work
virtual space -> NETWORK ACCESS
social -> space
consumer -> status
status -> physical space
status -> physical practices
physical space -> NETWORK ACCESS
fibre -> geography
"5G" -> geography
consumer -> government
government -> NETWORK ACCESS
consumer -> learning
learning -> social
broadcast -> "5G"
corporation -> NETWORK ACCESS
masts -> maintenance
wire -> maintenance
masts -> land
consumer -> collaboration
consumer -> NETWORK ACCESS
mobile -> geography
masts -> mobile
broadcast -> NTN (non terrestrial Network)
broadcast -> mobile
NTN (non terrestrial Network) -> SATELLITE
USER TERMINAL -> SATELLITE
groundstation -> SATELLITE
backhaul -> groundstation
LEO microsat -> phased array ANTENNAs
phased array ANTENNAs -> groundstation
LEO microsat -> launchers
LEO microsat -> ANTENNA
ANTENNA -> SPECTRUM
groundstation -> ANTENNA
phased array antennas -> beam_steering
beamforming -> phased array antennas
groundstation -> CONTROL SYSTEMS
SATELLITE -> CONTROL SYSTEMS
LEO microsat -> PROPULSION
PROPULSION -> fleet management
LEO microsat -> Sat2Satp
LEO microsat -> Optical Sat2Sat Coms
power -> SATELLITE
SATELLITE -> COOLING
LEO microsat -> automated factory
LEO microsat -> AUTOMATION

AUTOMATION -> supply chain awareness
supply chains -> supply chain awareness
AUTOMATION -> supply chains
component SPACE REGULATION [0.10, 0.39] label [-80, -34]
SPECTRUM -> SPACE REGULATION
orbit tracking -> SPACE REGULATION
SPACE REGULATION -> SPACE REGULATION

