wardley-beta
title AI, Societal Change, JUNE 2023
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity / accepted

anchor We [0.97, 0.47]
anchor Me [0.97, 0.73]

component Identity [0.91, 0.54] label [1, -19]

component BELONGING [0.86, 0.43] label [-70, -10]
pipeline BELONGING {
  component Companionship [0.24] label [-111, 0]
  component Role models [0.57] label [-39, -21]
  component Individualism [0.7] label [19, 1]
}

component Safety [0.79, 0.39] label [-54, 1]

component Power [0.79, 0.50] label [9, 2]

component ADVANTAGE [0.74, 0.39] label [-78, 3]
evolve ADVANTAGE 0.53
component Equality [0.74, 0.53] label [9, 0]

component PSYCHOLOGY [0.15, 0.60] label [11, -2]
pipeline PSYCHOLOGY {
  component Mimicary [0.5] label [-69, -4]
  component Mental Health [0.52] label [-112, 1]
  component fairness [0.68] label [21, 0]
}

component MACHINE LEARNING [0.55, 0.34] label [-6, -35]
pipeline MACHINE LEARNING {
  component AGI [0.11] label [-44, 0]
  component Accuracy [0.28] label [-55, -21]
  component Skill Augmentation [0.38] label [-34, 13]
  component LLM Model [0.55] label [-20, -19]
  component FOUNDATIONAL COMPONENTS [0.67] label [-21, -45]
}

component NATURAL LEARNING [0.46, 0.56] label [-4, -35]
pipeline NATURAL LEARNING {
  component Differentiated Learning [0.25] label [-102, -18]
  component Learning Tools [0.41] label [-94, 23]
  component Syllabus Learning [0.67] label [-1, -36]
  component Storytelling [0.81] label [-16, -23]
  component Ritual [0.87] label [-40, 24]
  component Symbols [0.89] label [24, 3]
}

component COMMUNITY [0.27, 0.42] label [-91, -5]
pipeline COMMUNITY {
  component Machine Mediated Community [0.18] label [-16, 13]
  component Social Media [0.56] label [-56, 24]
  component Open Source [0.67] label [-39, -20]
  component State Mediated community [0.73] label [-24, -61]
  component "Non-mediated community" [0.78] label [32, -16]
}

component MINDS [0.07, 0.43] label [-37, -13]
pipeline MINDS {
  component Artificial Minds [0.18] label [-82, -15]
  component Natural Minds [0.79] label [20, 0]
}

component LEGAL FRAMEWORKS [0.66, 0.50] label [-27, -40]
pipeline LEGAL FRAMEWORKS {
  component EU AI Act [0.29] label [-88, 1]
  component GDPR [0.4] label [-23, -20]
  component Common Law [0.72] label [-5, -20]
}

component AFFORDANCES [0.36, 0.50] label [-1, -12]
pipeline AFFORDANCES {
  component Societal Disadvantage [0.44] label [-10, 8]
  component Societal Biases [0.56] label [-29, 12]
  component public services [0.61] label [-34, -47]
  component Disparities [0.66] label [3, -21]
}

We -> Identity
Me -> Identity
Me -> Individualism
We -> Companionship

Self worth -> Me
Identity -> Belonging

Individual Biases -> Societal Biases

Power -> ADVANTAGE
Power -> Equality
Safety -> ADVANTAGE
Safety -> Equality
Learning Tools -> PSYCHOLOGY
Differentiated Learning -> PSYCHOLOGY

PSYCHOLOGY -> Mirroring
PSYCHOLOGY -> Mimicary
PSYCHOLOGY -> Syllabus Learning
Natural Minds -> "Non-mediated Community"
LLM Model -> Mimicary

Syllabus Learning -> Equality
Differentiated Learning -> ADVANTAGE

Machine Mediated Community -> Differentiated Learning

Common Law -> "Non-mediated community"
"Non-mediated community" -> Storytelling
"Non-mediated Community" -> Oral Tradition

Society Disadvantage -> ADVANTAGE
Individual Disadvantage -> Society Disadvantage

Identity -> BELONGING
BELONGING -> Safety
Power -> BELONGING
Power -> LEGAL FRAMEWORKS
ADVANTAGE -> LEGAL FRAMEWORKS
EU AI Act -> MACHINE LEARNING

Role models -> Storytelling
Societal Disadvantage -> Differentiated Learning
ADVANTAGE -> AFFORDANCES
Equality -> LEGAL FRAMEWORKS
Artificial Minds -> AGI
Mimicary -> Artificial Minds
BELONGING -> COMMUNITY
PSYCHOLOGY -> Natural Minds

