wardley-beta
title Cybersecurity, People, May 2023, version 0.3
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component External Users [0.95, 0.70]
component Internal Stakeholders [0.96, 0.63]
component company culture [0.95, 0.31]

component SITUATIONAL AWARENESS [0.71, 0.40]
pipeline SITUATIONAL AWARENESS {
  component cultural landscape [0.19]
  component supply chains [0.22]
  component economy [0.25]
  component SBOMs [0.41]
  component viral threats [0.64]
  component "building access" [0.68]
  component territorial maps [0.71]
}

component risk management [0.95, 0.58]
component Annualised Loss Expectancy [0.92, 0.43]
component ASSETS [0.85, 0.55]
pipeline ASSETS {
  component people [0.35]
  component reputation [0.38]
  component identity [0.41]
  component brand [0.47]
  component goodwill with regulators [0.62]
  component safety [0.66]
  component infrastructrue [0.68]
  component wealth [0.7]
}

component THREATS [0.24, 0.48]
pipeline THREATS {
  component Prompt Insertion [0.23]
  component IoT Surveillance [0.39]
  component behavioural attacks [0.42]
  component Deep Fakes [0.44]
  component Public image scraping [0.51]
  component social engineering [0.56]
  component malicious algorithms [0.64]
  component email phishing [0.7]
  component exploit toolkits [0.75]
  component "move fast & break things" [0.79]
  component tech debt [0.81]
  component cracking [0.86]
}

component PROTECTION [0.56, 0.58]
pipeline PROTECTION {
  component LEGISLATION [0.22]
  component Protective filters [0.25]
  component Data rights [0.29]
  component blast radius [0.34]
  component Privacy [0.39]
  component identity controls [0.53]
  component Enforcement resources [0.6]
  component GDPR [0.64]
  component Digital Signatures [0.72]
  component Antivirus [0.79]
}

component HUMAN SYSTEM INTERACTION [0.42, 0.40]
pipeline HUMAN SYSTEM INTERACTION {
  component AI content interaction [0.18]
  component Human error [0.32]
  component spotting shadow IT [0.42]
  component misconfiguration [0.44]
  component human to human interaction [0.71]
}

component DATA ACCESS [0.08, 0.27]
pipeline DATA ACCESS {
  component PUBLIC KNOWLEDGE [0.18]
  component ethics [0.34]
  component personal [0.39]
  component ease of access [0.51]
  component intellectual property [0.64]
}

External Users -> safety
Internal Stakeholders -> risk management
SITUATIONAL AWARENESS -> risk management
safety -> risk management
risk management -> Annualised Loss Expectancy
risk management -> ASSETS
risk management -> company culture
risk management -> "brand / ASSETS"
safety -> ASSETS
safety -> PROTECTION
PROTECTION -> THREATS
PROTECTION -> DATA ACCESS
HUMAN SYSTEM INTERACTION -> PROTECTION
HUMAN SYSTEM INTERACTION -> THREATS
SITUATIONAL AWARENESS -> PROTECTION
ASSETS -> SITUATIONAL AWARENESS

