wardley-beta
title Cybersecurity - May 2023 - Security Awareness - v3.2
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity / accepted

anchor Employee [0.99, 0.50]
anchor "CISO/Legal Counsel" [1.00, 0.60]

component security awareness (metric) [0.92, 0.67] label [9, -41]
component EXPECTATIONS [0.87, 0.45] label [-21, -14]
pipeline EXPECTATIONS {
  component "personal/family choice" [0.22] label [-105, -17]
  component society [0.4] label [-31, -19]
  component coporporate [0.73] label [19, 0]
}

component cultural norms [0.76, 0.27] label [-109, 2]

component SECURITY PRACTICES [0.70, 0.55] label [-31, -36]
pipeline SECURITY PRACTICES {
  component responsible disclosure [0.28] label [-93, -18]
  component ethical hacking [0.34] label [-46, -42]
  component detecting org specific risks [0.37] label [-21, -73]
  component MFA [0.52] label [-11, 25]
  component VPN [0.65] label [-13, -20]
  component general security behaviors [0.69] label [-15, -54]
  component password rules [0.8] label [-74, -20]
  component password hygiene [0.82] label [-18, 14]
  component "best/standard practices" [0.89] label [31, -10]
}

component TRAINING [0.47, 0.66] label [-31, -15]
pipeline TRAINING {
  component customized content [0.24] label [-87, -12]
  component gamification [0.35] label [-31, -20]
  component social engineering [0.46] label [-19, -46]
  component learning from past incidents [0.56] label [-9, -73]
  component video content [0.73] label [-80, 25]
  component written content [0.77] label [-29, -43]
  component standard content [0.87] label [17, -13]
}

component "CMS/Application" [0.18, 0.92] label [-54, 11]

component TESTING [0.34, 0.51] label [-40, -12]
pipeline TESTING {
  component "physical/ anti-tailgating testing" [0.19] label [-106, -26]
  component voice phishing [0.28] label [-48, -19]
  component "(multi-channel) Social engineering" [0.36] label [-28, -60]
  component spoofing [0.85] label [-43, -19]
  component "email/sms phishing" [0.88] label [-27, 16]
  component impersonation [0.91] label [-40, -20]
  component survey [0.94] label [19, 4]
}

note "skills shortage" [0.29, 0.37]

component THREAT [0.17, 0.52] label [-59, -5]

component SECURITY CENTRE OF EXCELLENCE [0.58, 0.36] label [-83, -57]
pipeline SECURITY CENTRE OF EXCELLENCE {
  component start-up [0.19] label [-81, 1]
  component hyperscale [0.43] label [-27, -19]
  component corporate [0.63] label [-22, -18]
}
evolve detecting org specific risks 0.50

annotations [0.94, 0.02]

component AI (DEEP FAKES) [0.06, 0.24] label [-33, -52]
pipeline AI (DEEP FAKES) {
  component non-celebrity deep fake [0.16] label [-86, -27]
  component celebrity deep-fake [0.35] label [-29, -42]
}
note "uncanny valley" [0.01, 0.37]

Employee -> EXPECTATIONS
"CISO/Legal Counsel" -> EXPECTATIONS
"CISO/Legal Counsel" -> security awareness (metric)
"CISO/Legal Counsel" -> detecting org specific risks t

EXPECTATIONS -> cultural norms
EXPECTATIONS -> SECURITY PRACTICES

security awareness (metric) -> EXPECTATIONS
security awareness (metric) -> SECURITY PRACTICES
security awareness (metric) -> SECURITY CENTRE OF EXCELLENCE
security awareness (metric) -> TRAINING
security awareness (metric) -> TESTING

TRAINING -> THREAT
TESTING -> THREAT

SECURITY PRACTICES -> TRAINING
TRAINING -> TESTING

detecting org specific risks -> THREAT

"(multi-channel) Social engineering" -> non-celebrity deep fake

voice phishing -> non-celebrity deep fake
THREAT -> AI (DEEP FAKES)

standard content -> "CMS/Application"
video content -> "CMS/Application"
written content -> "CMS/Application"

evolve non-celebrity deep fake 0.5
evolve voice phishing 0.7
evolve "(multi-channel) Social engineering" 0.6

