wardley-beta

title ENERGY - disruption, JULY 2022
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity / accepted

note ">110kV" [0.30, 0.35]
note "<110kV" [0.36, 0.60]

component awareness [0.50, 0.31] label [-78, 2]
component supply chain [0.40, 0.42] label [-101, 4]

component USER [0.94, 0.54]
pipeline USER {
  component tomorrow [0.42] label [-75, 3]
  component today [0.63] label [18, 5]
}
component COST [0.72, 0.63] label [-4, -11]
pipeline COST {
  component externality [0.43] label [-98, 9]
  component price [0.69] label [17, 3]
}
component transmission [0.32, 0.41] label [-97, 0]
component capital [0.06, 0.72] label [8, 4]
component protection system [0.04, 0.27] label [-79, -12]

component RESERVE [0.02, 0.70] label [9, 7]

component distribution [0.35, 0.63] label [-93, 11]
component landscape [0.12, 0.25] label [-78, -1]

component ENERGY USAGE [0.57, 0.65] label [11, 4]
component ENERGY MIX [0.43, 0.67] label [12, -5]
pipeline ENERGY MIX {
  component renewable [0.6] label [-83, 0]
  component fossil [0.73] label [17, 4]
}

note "(grid)" [0.38, 0.38]

component ENERGY PRODUCTION [0.13, 0.68] label [-62, -37]
pipeline ENERGY PRODUCTION {
  component nuclear [0.38] label [-69, 5]
  component solar collectors [0.41] label [-40, 13]
  component gas [0.44] label [-7, -20]
  component solar microgen [0.74] label [17, 4]
}
component ENERGY GENERATION [0.51, 0.65] label [-71, -29]
pipeline ENERGY GENERATION {
  component OTC market [0.59] label [-88, 3]
  component spotmarket [0.7] label [-21, -17]
  component public good [0.78] label [16, 4]
}

component BATTERY (POWER) STORAGE [0.25, 0.57] label [-57, -45]
pipeline BATTERY (POWER) STORAGE {
  component synthetic [0.2] label [-83, 1]
  component hydrogen [0.4] label [-25, 22]
  component potential energy [0.53] label [-49, 13]
  component electrical [0.7] label [15, 7]
}
component SURVIVABILITY [0.82, 0.55] label [-100, -12]
pipeline SURVIVABILITY {
  component sustainability [0.43] label [-122, -2]
  component security [0.68] label [20, 4]
}
component education [0.74, 0.35] label [-79, 1]
component CO2 [0.60, 0.49] label [-36, 5]

component CONTROL [0.63, 0.64] label [-63, -7]
pipeline CONTROL {
  component regulation [0.6] label [-89, 5]
  component "market" [0.69] label [19, 4]
}

evolve transmission 0.49
evolve distribution 0.75
note "+constraint" [0.30, 0.66]

society -> consumers
consumers -> behaviour
society -> survival
mkt_competition -> ENERGY USAGE
education -> efficiency
behaviour -> expectations
political -> expectations
ENERGY USAGE -> ENERGY GENERATION
ENERGY GENERATION -> ENERGY MIX
renewable -> BATTERY (POWER) STORAGE
ENERGY MIX -> ENERGY PRODUCTION
efficiency -> ENERGY USAGE
eco luddites -> expectations
expectations -> history
generators -> ENERGY USAGE
government -> society
government -> political
government -> regulation
mkt_competition -> "other"
ENERGY GENERATION -> supply chain
regulation -> awareness
awareness -> awareness
supply chain -> awareness
encumbents -> ENERGY USAGE
consumers -> mkt_competition
providers -> mkt_competition
sustainability -> education
sustainability -> renewable
tomorrow -> sustainability
sustainability -> externality
USER -> behaviour
behaviour -> COST
price -> "market"
externality -> regulation
today -> security
security -> price
security -> ENERGY USAGE
USER -> SURVIVABILITY
SURVIVABILITY -> COST
SURVIVABILITY -> CONTROL
ENERGY MIX -> transmission
transmission -> protection system
ENERGY PRODUCTION -> capital
capital -> transmission
capital -> BATTERY (POWER) STORAGE
distribution -> ENERGY MIX
supply chain -> transmission
supply chain -> distribution
distribution -> capital
transmission -> landscape
RESERVE -> gas
externality -> CO2

CO2 -> ENERGY MIX

