wardley-beta
title HEALTHCARE - AI - Feb, 2023
size [1100, 800]

evolution genesis / concept -> custom / emerging -> product / converging -> commodity / accepted

component patient [0.97, 0.64] label [13, 0]

component AI CAPABILITY [0.52, 0.60] label [-54, -10]
pipeline AI CAPABILITY {
  component complex demand simulation (digital twins) [0.21] label [-78, -21]
  component explainability [0.25] label [-94, -13]
  component precision medicine [0.26] label [-46, 11]
  component clinical notes [0.36] label [-92, -20]
  component clinical decision making [0.42] label [-49, 11]
  component clinical support [0.46] label [-14, -43]
  component pathway management [0.51] label [-46, 15]
  component micro expression analysis [0.56] label [-22, 13]
  component doc scan [0.62] label [-29, 23]
  component voice [0.65] label [-13, -20]
  component object recognition [0.68] label [-33, 13]
  component predictive analytics [0.7] label [-13, -43]
  component categorisation [0.74] label [16, 3]
}

component DATA [0.20, 0.68] label [3, -11]
pipeline DATA {
  component unstructured [0.57] label [-105, 5]
  component structured [0.73] label [16, 0]
}
component STANDARDS [0.12, 0.47] label [0, -8]
pipeline STANDARDS {
  component EHR [0.39] label [-38, 0]
  component general practice EHR [0.59] label [-45, 16]
  component financial codes [0.62] label [-39, -41]
  component snomed [0.65] label [-15, 22]
  component digital pathology [0.69] label [-26, -45]
  component PACS [0.72] label [17, 5]
}

component AI [0.39, 0.63] label [-22, -10]
pipeline AI {
  component General purpose [0.16] label [-74, -12]
  component regulators [0.3] label [-77, -3]
  component regulation [0.32] label [-76, -3]
  component deep learning [0.52] label [-86, -20]
  component machine learning [0.71] label [22, -12]
}
component HCI [0.72, 0.54] label [-18, -11]
pipeline HCI {
  component replace people [0.37] label [-122, 3]
  component augment tasks [0.56] label [-29, 24]
  component replace tasks [0.58] label [13, 5]
}

component ETHICS [0.63, 0.43] label [-45, -9]
pipeline ETHICS {
  component consent [0.35] label [-66, 5]
  component bias [0.39] label [-9, 18]
  component audit [0.45] label [16, -6]
}
component TRAINING DATA [0.24, 0.36] label [-103, -9]
pipeline TRAINING DATA {
  component intersectionality [0.23] label [-107, -5]
  component anonymised training sets [0.39] label [25, -9]
}
component history [0.17, 0.38] label [-61, 6]
component HEALTHCARE [0.90, 0.61] label [-77, -8]
pipeline HEALTHCARE {
  component triage [0.56] label [-62, 5]
  component health [0.64] label [9, 8]
  component diagnosis [0.68] label [18, 4]
}
component PROVIDER [0.82, 0.60] label [7, -5]
pipeline PROVIDER {
  component virtual assistant [0.41] label [-91, -13]
  component chatbot [0.53] label [-57, 21]
  component clinician [0.69] label [16, 3]
}
component data store [0.05, 0.72] label [15, 15]
component trust [0.93, 0.47] label [-35, -10]

component MODEL [0.31, 0.42] label [-37, -9]
pipeline MODEL {
  component "pre-trained models" [0.45] label [28, 5]
}
evolve deep learning 0.67
evolve "pre-trained models" 0.65
evolve EHR 0.45
evolve chatbot 0.6

patient -> trust
patient -> health
health -> HEALTHCARE
diagnosis -> clinician
diagnosis -> virtual assistant
triage -> chatbot
clinician -> replace tasks
virtual assistant -> replace people
clinician -> HCI
clinician -> augment tasks
HCI -> ETHICS
replace people -> bias
HCI -> AI CAPABILITY
augment tasks -> object recognition
replace tasks -> categorisation
replace tasks -> doc scan
augment tasks -> clinical notes
augment tasks -> pathway management
augment tasks -> clinical decision making
object recognition -> machine learning
AI CAPABILITY -> AI
categorisation -> machine learning
doc scan -> machine learning
virtual assistant -> General purpose
clinical decision making -> deep learning
bias -> explainability
audit -> explainability

AI -> MODEL
TRAINING DATA -> DATA
DATA -> data store
structured -> financial codes
DATA -> STANDARDS
unstructured -> EHR
TRAINING DATA -> history
bias -> history
audit -> regulation
chatbot -> pathway management
consent -> DATA
trust -> ETHICS
audit -> AI CAPABILITY
HEALTHCARE -> PROVIDER
regulation -> STANDARDS
regulation -> regulators

object recognition -> deep learning
AI CAPABILITY -> regulation
MODEL -> TRAINING DATA

