wardley-beta

title GOVERNMENT - IDENTITY - NOV 2022
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product / converging -> commodity/ accepted

component bad actor [0.97, 0.50] label [-62, 6]
component government [0.98, 0.61] label [-30, 42]
component society [0.96, 0.67] label [9, -4]
component ENTITY [0.90, 0.72] label [0, -11]
note "(subordinate)" [0.89, 0.73]
note "(reliant party)" [0.83, 0.72]
note "(issuing party == ENTITY)" [0.21, 0.62]
note "(what I am)" [0.70, 0.77]

component claim [0.79, 0.68] label [10, 3]

component POWER [0.06, 0.66] label [-55, -26]
pipeline POWER {
  component symbolic [0.51] label [-76, 3]
  component exception [0.55] label [-76, -16]
  component to [0.57] label [2, -19]
  component over [0.63] label [-12, 28]
  component with [0.68] label [21, 2]
}

component regulators (authorities) [0.79, 0.40] label [-82, -6]

component services [0.86, 0.72] label [8, 9]
component IDENTITY [0.69, 0.72] label [8, -10]
pipeline IDENTITY {
  component digital material [0.64] label [-78, -17]
  component collective (company) [0.68] label [-40, -46]
  component physical material [0.71] label [-6, 40]
  component people [0.74] label [16, -2]
}

component credential [0.33, 0.62] label [-5, 31]

component IDENTIFICATION [0.53, 0.73] label [-22, -14]
pipeline IDENTIFICATION {
  component physical [0.67] label [-51, -22]
  component digital [0.76] label [19, 1]
}
component AUTHORITY [0.26, 0.68] label [11, 44]
pipeline AUTHORITY {
  component decentralised authority [0.42] label [-95, -21]
  component centralised authority [0.75] label [27, -15]
}

component IDENTIFIERS [0.43, 0.61] label [-79, -10]
pipeline IDENTIFIERS {
  component connectedness (FOAF) [0.47] label [-60, 28]
  component immutable (facial geometry) [0.64] label [20, 29]
  component mutable (name) [0.7] label [-1, 44]
}

component rules [0.14, 0.58] label [5, 10]

component regulation [0.89, 0.45] label [-84, 5]

component TRUST [0.17, 0.43] label [-47, -5]
pipeline TRUST {
  component INTEGRITY [0.37] label [-81, 5]
  component BENEVOLENCE [0.45] label [-41, 24]
  component CAPABILITY [0.52] label [-8, -18]
}

component situation [0.03, 0.25] label [-81, 2]

component TRANSPORT LAYER [0.45, 0.77] label [13, -4]

note "(e.g. internet)" [0.42, 0.82]

government -> services
citizen -> services
avoiding harm -> regulation
governance -> avoiding harm
governance -> government
TRUST -> narratives
biometric -> storage
narratives -> ethics
avoiding harm -> POWER over
POWER over -> self sovereign
government -> POWER over
corporations -> POWER over
government -> society
permission to act -> centralised AUTHORITY
government -> regulation
citizen -> avoiding harm
self sovereign -> freedom
POWER -> ethics
freedom -> self IDENTITY
privacy -> digital IDENTITY
privacy -> centralised paper
self sovereign -> decentralised authority
permission to modify -> centralised AUTHORITY
regulation -> regulators (authorities)
regulators (authorities) -> permission to act
privacy -> centralised AUTHORITY
corporations -> centralised AUTHORITY
IDENTIFICATION -> biometric
POWER -> AUTHORITY
centralised AUTHORITY -> issuing AUTHORITY
consensus alogrithm -> decentralised authority
decentralised authority -> self signed
issuing AUTHORITY -> exclusion
society -> ENTITY
ENTITY -> services
services -> services
services -> claims
claims -> IDENTITY
claims -> AUTHORITY
services -> claims of credentials
claims of credentials -> IDENTITY
claims of credentials -> token
token -> AUTHORITY
services -> claim
claim -> IDENTITY
claim -> credential
AUTHORITY -> credential
evidence -> IDENTIFICATION
IDENTIFICATION -> credential
IDENTIFICATION -> IDENTIFIERS
collective (company) -> connectedness (FOAF)
people -> IDENTIFICATION
material -> physical
physical material -> physical
digital material -> digital
regulation -> rules
AUTHORITY -> rules
rules -> exception
corporate -> services
bridge -> services
services -> robots
river -> services
digital -> physical material
digital -> collective (company)
bad actor -> rules
bad actor -> TRUST
AUTHORITY -> TRUST
bad actor -> claim
TRUST -> awareness of context
TRUST -> situation
TRANSPORT LAYER -> digital

