wardley-beta
title Game & Experience Design
size [1100, 800]

component gamers [0.98, 0.85] label [13, -2]

component designers [0.98, 0.47] label [9, 6]
component vision [0.77, 0.51] label [20, -32]
designers -> vision
gamers -> experience

component technical platforms [0.05, 0.84] label [7, -27]
pipeline technical platforms {
  component custom [0.37] label [1, -15]
  component unreal [0.67] label [-40, 24]
  component unity [0.68] label [-2, 31]
  component roblox [0.69] label [17, 12]
}
component distribution platforms [0.19, 0.76] label [14, -14]
pipeline distribution platforms {
  component webpage [0.44] label [4, 31]
  component streaming platforms [0.88] label [-57, 42]
  component "play store, apple store," [0.91] label [-78, 28]
}
component game engine [0.12, 0.67] label [21, 6]
component game mechanics [0.59, 0.44] label [12, 6]
component world building [0.65, 0.47] label [-21, 18]
component story [0.71, 0.38] label [-4, -39]
pipeline story {
  component artisan [0.31] label [-67, 10]
  component continous challenge [0.53] label [32, -39]
  component progression [0.62] label [-47, -21]
  component genre [0.76] label [0, -20]
  component conveyor belt [0.79] label [18, -2]
}
component monetisation strategy [0.41, 0.74] label [3, -22]
pipeline monetisation strategy {
  component pay to win [0.68] label [-36, -20]
  component ads [0.71] label [-34, 31]
  component subscription [0.79] label [19, -4]
}
component streamers [0.97, 0.71] label [-65, 44]
component watchers [0.96, 0.91] label [-8, -10]
streaming platforms -> watchers
streaming platforms -> streamers
component target audience [0.56, 0.43] label [-66, 42]
vision -> story
story -> target audience
component producers [0.99, 0.42] label [-71, 7]
producers -> monetisation strategy
vision -> game mechanics
story -> world building
story -> game mechanics

drama -> story
gamers -> experience
watchers -> drama
watchers -> tension
streamers -> monetisation strategy
component tension creation [0.77, 0.24] label [-63, -16]
vision -> tension creation
tension creation -> story
component coop vs competitive [0.43, 0.47] label [-57, -16]
component betatesting [0.49, 0.76] label [5, -32]
story -> betatesting
component data [0.53, 0.65] label [-24, -8]
betatesting -> data
component modders [0.98, 0.56] label [15, 6]
modders -> game engine
component evaluation [0.62, 0.76] label [-5, -19]
evaluation -> betatesting
story -> evaluation
evaluation -> data
component "build release cycle" [0.63, 0.55] label [-2, -22]
story -> "build release cycle"
component profit [0.79, 0.69] label [-43, 31]
designers -> profit
producers -> profit
streamers -> profit
profit -> monetisation strategy
monetisation strategy -> game engine
monetisation strategy -> distribution platforms
monetisation strategy -> streaming platforms
monetisation strategy -> technical platforms
component agency [0.73, 0.28] label [-62, 0]
drama -> agency
dopamine -> agency
social -> agency
gamers -> agency
designers -> story
betatesting -> target audience
component "marketing" [0.31, 0.59] label [-33, -48]
pipeline "marketing" {
  component growth hacking [0.34] label [-65, 28]
  component nurturing habits [0.68] label [-23, 31]
  component crossselling [0.79] label [23, 4]
}
target audience -> "marketing"
game mechanics -> coop vs competitive

game engine -> technical platforms
distribution platforms -> technical platforms
monetisation strategy -> "marketing"
component experience [0.92, 0.32] label [-16, -12]
pipeline experience {
  component status [0.23] label [-28, -21]
  component mod support [0.25] label [-36, 25]
  component disconnect from life [0.27] label [-43, -41]
  component control [0.32] label [-26, 24]
  component dopamine [0.38] label [-96, -16]
  component drama [0.39] label [2, 28]
  component social [0.46] label [-20, 24]
  component tension [0.49] label [5, 24]
}
profit -> monetisation strategy
coop vs competitive -> game engine
coop vs competitive -> technical platforms
component empathy [0.49, 0.24] label [-47, -14]
story -> empathy
target audience -> empathy
evaluation -> empathy
component "story building (?)" [0.59, 0.27] label [-65, -17]
story -> "story building (?)"
"story building (?)" -> empathy
drama -> tension creation
tension -> tension creation
dopamine -> tension creation
tension creation -> agency
agency -> story
agency -> game mechanics
profit -> evaluation
target audience -> data
component "in game monitoring (?)" [0.44, 0.24] label [-53, -8]
data -> "in game monitoring (?)"
empathy -> "in game monitoring (?)"
component game context monitoring [0.43, 0.28] label [-53, 22]
empathy -> game context monitoring
designers -> game context monitoring
story -> game context monitoring
world building -> game mechanics
producers -> "in game monitoring (?)"
modders -> status
modders -> social
modders -> mod support
vision -> empathy
continous challenge -> "build release cycle"
component developers [0.99, 0.64] label [24, 6]

