wardley-beta
title Individual Learning V2
size [1100, 800]

component Motivation [0.97, 0.60] label [24, 6]
component Job [0.96, 0.85] label [-9, -16]
component Joy of Learning [0.96, 0.34] label [-45, -16]
component Min Time [0.96, 0.39] label [12, 6]
evolve Min Time 0.74

component Bloom [0.75, 0.66] label [1, -10]
component Mastery [0.73, 0.83] label [-24, -19]
component Overview [0.74, 0.47] label [-10, -18]

component Social Capabilties [0.47, 0.47] label [-1, -36]
pipeline Social Capabilties {
  component Online Simulations [0.38] label [-20, -43]
  component Coaching [0.83] label [-13, -20]
}
evolve Online Simulations 0.61

component Find the Right Curse [0.59, 0.61] label [-6, -62]
component Peers [0.58, 0.82] label [-16, -20]
component Google for Education [0.58, 0.33] label [-33, -60]
evolve Google for Education 0.77

component Learn everythere [0.87, 0.50] label [-29, -33]
component Apple Glasses [0.85, 0.33] label [-37, -22]
component mobile [0.85, 0.56] label [-21, -22]
component VR [0.85, 0.41] label [-8, -21]
evolve VR 0.6
evolve Apple Glasses 0.66

component Curriculum [0.35, 0.62] label [-30, -14]
component interactive personalized [0.33, 0.34] label [-30, -49]
evolve interactive personalized 0.77

component fix Curriculum [0.33, 0.82] label [-3, -22]

component Status [0.24, 0.59] label [-18, -48]
pipeline Status {
  component Self Learning [0.32] label [-26, -20]
  component Independet RockStars MOOCs [0.38] label [-10, -60]
  component Elite Badge Certification [0.8] label [-43, -45]
}
evolve Independet RockStars MOOCs 0.69

component Tech Stack [0.11, 0.64] label [-20, -23]
component "LMS, LXP" [0.10, 0.82] label [-27, -20]
component Adaptive Learning Engine [0.10, 0.34] label [-27, -59]
evolve Adaptive Learning Engine 0.77
component PKM [0.10, 0.43] label [-8, -17]
evolve PKM 0.61

Find the Right Curse -> Curriculum
Bloom -> Curriculum
Curriculum -> Status
Status -> Tech Stack
Curriculum -> Tech Stack
Learn everythere -> Curriculum
Mastery -> Curriculum
Mastery -> Status
Overview -> fix Curriculum
Min Time -> interactive personalized
Find the Right Curse -> Social Capabilties
Min Time -> Learn everythere
Motivation -> Bloom
Job -> Status

Min Time -> PKM
interactive personalized -> Adaptive Learning Engine

