wardley-beta

title  education - general
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component "individual" [0.82, 0.69]
component "social cohesion" [0.90, 0.58]
pipeline "social cohesion" {
  component "regulated jobs" [0.44]
  component "community" [0.56]
  component "behaviors" [0.61]
  component "economic growth" [0.73]
}
component "student" [0.73, 0.62]
pipeline "student" {
  component "adhoc" [0.35]
  component "assessment" [0.58]
  component "employee" [0.72]
}
component "employer" [0.97, 0.66]
component "education" [0.53, 0.59]
pipeline "education" {
  component "micro learning" [0.35]
  component "verification" [0.39]
  component "degree" [0.68]
  component "micro credentials" [0.74]
}
component "digital identity" [0.22, 0.46]
component "certification" [0.43, 0.60]
component "regulation" [0.79, 0.40]
component "government" [0.97, 0.62]
component "identity" [0.16, 0.68]
component "educator" [0.10, 0.68]
pipeline "educator" {
  component "AI tutors" [0.2]
  component "community learning" [0.55]
  component "online" [0.64]
  component "physical" [0.72]
}
component "status" [0.28, 0.46]
pipeline "status" {
  component "badges" [0.36]
  component "institution" [0.55]
}

component "evidence" [0.63, 0.36]

component "curriculum" [0.37, 0.41]
pipeline "curriculum" {
  component "informal" [0.19]
  component "standards" [0.55]
  component "formal" [0.72]
}

component "leaderboard" [0.16, 0.28]
component "brand" [0.03, 0.50]

component "power" [0.61, 0.61]
pipeline "power" {
  component "inclusion" [0.51]
  component "skills" [0.67]
  component "exclusion" [0.69]
}

note "+componentization" [0.48, 0.73]

evolve "degree" 0.74

"experience" -> "employee"
"economic growth" -> "skills"
"curriculum" -> "educator"
"brand" -> "institution"
"Synthetic tutors" -> "AI tutors"
"status" -> "rockstar tutors"
"employer" -> "skills"
"employer" -> "assessment"
"assessment" -> "education"
"assessment" -> "verification"
"digital identity" -> "online"
"digital identity" -> "identity"
"identity" -> "educator"
"certification" -> "verification"
"education" -> "certification"
"regulated jobs" -> "certification"
"regulated jobs" -> "regulation"
"regulation" -> "standards"
"employee" -> "certification"
"skills" -> "certification"
"certification" -> "educator"
"lifelong" -> "education"
"micro learning" -> "online"
"certification" -> "status"
"skills" -> "status"
"institution" -> "physical"
"badges" -> "digital identity"
"verification" -> "standards"
"verification" -> "identity"
"community" -> "student"
"community" -> "participation"
"community" -> "inclusion"
"skills" -> "exclusion"
"exclusion" -> "identity"
"community" -> "social learning"
"assessment" -> "evidence"

"curriculum" -> "education"
"student" -> "status"
"status" -> "status"
"leaderboard" -> "status"
"leaderboard" -> "evidence"
"brand" -> "rockstar tutors"
"status" -> "brand"

"student" -> "skills"
"government" -> "authority"
"authority" -> "power"
"government" -> "social control"
"government" -> "social cohesion"
"individual" -> "economic growth"
"individual" -> "adhoc"
"individual" -> "community"
"adhoc" -> "micro credentials"
"certification" -> "formal"
"certification" -> "standards"
"power" -> "curriculum"

"skills" -> "education"
"behaviors" -> "individual"

