wardley-beta
title Education (a power struggle)
size [1100, 800]

component government [0.98, 0.72] label [24, 6]
component advantage [0.94, 0.46] label [-11, -10]
component economic growth [0.84, 0.38] label [9, 6]
component elite [0.87, 0.65] label [7, 6]
component status [0.61, 0.62] label [7, -19]
component institutions [0.20, 0.70] label [18, 6]
component community [0.88, 0.85] label [-11, -10]
component shared values [0.33, 0.82] label [-1, -32]
component companies [0.71, 0.49] label [-27, -30]
component learner [0.44, 0.56] label [4, -19]
component motivation [0.32, 0.64] label [-30, 28]
component challenge [0.32, 0.22] label [27, 6]
component experience [0.03, 0.32] label [24, 6]
component stability [0.31, 0.55] label [11, -3]
component tutor [0.12, 0.45] label [23, -32]
component exclusion [0.70, 0.74] label [-42, -12]
component inclusion [0.70, 0.77] label [5, 20]

government -> advantage
government -> community
government -> elite
elite -> exclusion
exclusion -> companies

advantage -> economic growth
economic growth -> companies
economic growth -> challenge
companies -> learner
companies -> stability
community -> shared  values
elite -> status
elite -> companies
status -> institutions
shared values -> institutions
motivation -> shared values
learner -> motivation
community -> inclusion
inclusion -> shared values
inclusion -> motivation
economic growth -> stability
learner -> stability
learner -> challenge
learner -> tutor
challenge -> experience
tutor -> experience
stability -> institutions
tutor -> institutions

