wardley-beta
title Livable earth/Nature sustainability, Sept 2023
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component "life on Earth" [0.83, 0.15]
pipeline "life on Earth" {
  component "resource" [0.72]
  component "<- life towards genesis" [0.72]
}

note "(corporations)" [0.87, 0.67]
note "(local communities)" [0.86, 0.11]

component "nutrition" [0.73, 0.15]
pipeline "nutrition" {
  component "soylent" [0.72]
  component "locally grown food" [0.72]
}
note "<- towards genesis" [0.74, 0.50]

component "breathable atmosphere" [0.60, 0.77]

component "social equity" [0.47, 0.22]
component "availability/covenience" [0.47, 0.22] (inertia)
component "sustainable choices" [0.44, 0.22] (inertia)

component "novel foods (impossible burger)" [0.35, 0.17]

component "chaotic disruption (covid-19)" [0.66, 0.06]

component "bioregionality" [0.77, 0.07]

component "non-potable water" [0.53, 0.84]
component "technology" [0.54, 0.56]
component "education" [0.32, 0.57]
component "Funding" [0.19, 0.31]
component "policy" [0.50, 0.43]
component "sunlight" [0.28, 0.78]
component "gravity" [0.23, 0.80]
component "effective measurement" [0.12, 0.07]
component "public perception" [0.59, 0.17]
component "sustainable energy" [0.54, 0.37]

