wardley-beta

title retail - SUSTAINABILITY, Jul 2022
size [1100, 800]
evolution genesis / concept -> custom / emerging -> product/ converging -> commodity / accepted

component corporation [0.75, 0.59] label [9, 3]
component government [1.00, 0.58] label [-14, 22]

component ESG [0.09, 0.44] label [-25, -12]
pipeline ESG {
  component customer [0.39] label [-73, 3]
  component suppliers [0.45] label [-52, 29]
  component internal [0.5] label [21, -1]
}
component GOAL [0.70, 0.47] label [-18, -15]
pipeline GOAL {
  component carbon neutral [0.368] label [-114, 1]
  component survival [0.52] label [-45, 24]
  component resilience [0.57] label [-29, 25]
  component KPI [0.66] label [5, 30]
  component cost optimisation [0.712] label [49, 34]
}
component supply chain [0.29, 0.64] label [7, 6]
component sanctions [0.70, 0.21] label [-77, 3]
component AWARENESS [0.39, 0.50] label [-13, -12]
pipeline AWARENESS {
  component supply chain awareness [0.298] label [-73, -21]
  component territorial awareness [0.692] label [24, -5]
}
component SOVEREIGNTY [0.83, 0.60] label [-65, -8]
pipeline SOVEREIGNTY {
  component political [0.448] label [-79, 2]
  component economy [0.59] label [-67, 29]
  component territorial [0.782] label [18, 5]
}
component CORPORATE SOVEREIGNTY [0.53, 0.46] label [20, -30]
pipeline CORPORATE SOVEREIGNTY {
  component environment [0.368] label [-93, 3]
  component social [0.48] label [8, 29]
  component economic [0.582] label [18, 8]
}
component transparency [0.30, 0.23] label [-95, 7]
component "labelling" [0.82, 0.30] label [-75, -4]
component REGULATION [0.23, 0.35] label [-18, -14]
pipeline REGULATION {
  component self [0.269] label [-48, 5]
  component gov [0.412] label [22, -6]
}
component MATERIALS [0.20, 0.63] label [-49, 19]
component ENERGY [0.20, 0.66] label [10, 18]
component BEHAVIOUR [0.94, 0.64] label [-52, -9]
pipeline BEHAVIOUR {
  component community [0.408] label [-85, 0]
  component convenience [0.61] label [-80, 28]
  component public [0.68] label [8, -14]
  component price [0.692] label [17, 2]
}
component trust [0.15, 0.32] label [-47, 3]

meeting a measure -> ESG
corporation -> GOAL
sustainability -> CORPORATE SOVEREIGNTY
environment -> carbon neutral
carbon neutral -> carbon neutral
economic -> supply chain
supply chain -> suppliers
supply chain -> advantage
consumers -> "labelling"
"labelling" -> transparency
government -> SOVEREIGNTY
corporation -> economy
political -> gov
profit -> advantage
consumer -> BEHAVIOUR
community -> environment
community -> "labelling"
price -> profit
price -> environment
price -> political
political -> sanctions
corporation -> profit
supply chain -> supply chain awareness
environment -> supply chain awareness
sanctions -> supply chain awareness
KPI -> ESG
price -> cost
cost -> supply chain
resilience -> economic
survival -> CORPORATE SOVEREIGNTY
supply chain awareness -> transparency
territorial -> territorial awareness
MATERIALS -> supply chain
ENERGY -> supply chain
REGULATION -> transparency
REGULATION -> trust
ESG -> trust
citizen -> BEHAVIOUR
public -> BEHAVIOUR
government -> public
cost optimisation -> price
cost optimisation -> supply chain
CORPORATE SOVEREIGNTY -> ESG

